name: Test WorldQuant Alphas

on:
  workflow_dispatch: # This enables the manual "Run workflow" button in GitHub Actions

jobs:
  run-backtest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: |
          pip install pandas numpy pyarrow requests tqdm plotly joblib yfinance paramiko scipy

      - name: Download Pricing Data
        run: python yfinance_download.py --input top_5000_us_by_marketcap.csv --output all_prices_5000_tickers.parquet

      - name: Create Universe and Returns
        run: python 1_create_universe_and_returns.py

      - name: Run WorldQuant Alpha Sector Backtest
        run: python 5_test_worldquant_alphas.py
